# Generated by Django 4.2.16 on 2026-05-28 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(blank=True, max_length=300)),
                ('sed_ide_siggo', models.IntegerField(blank=True, db_index=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UnidadOrganica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('abreviatura', models.CharField(blank=True, max_length=20)),
                ('nivel', models.IntegerField(default=1)),
                ('uni_ide_siggo', models.IntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('superior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinadas', to='organizacion.unidadorganica')),
            ],
            options={
                'verbose_name': 'Unidad Orgánica',
                'verbose_name_plural': 'Unidades Orgánicas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Subgerencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('unidad_organica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgerencias', to='organizacion.unidadorganica')),
            ],
            options={
                'verbose_name': 'Subgerencia',
                'verbose_name_plural': 'Subgerencias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('subgerencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencias', to='organizacion.subgerencia')),
            ],
            options={
                'verbose_name': 'Dependencia',
                'verbose_name_plural': 'Dependencias',
                'ordering': ['nombre'],
            },
        ),
    ]
