# Generated by Django 4.2.16 on 2026-05-28 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('organizacion', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BienBaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sin_registro', models.BooleanField(default=False)),
                ('sr_cod_inventario', models.CharField(blank=True, max_length=100)),
                ('sr_descripcion', models.CharField(blank=True, max_length=300)),
                ('sr_marca', models.CharField(blank=True, max_length=100)),
                ('sr_modelo', models.CharField(blank=True, max_length=150)),
                ('sr_serie', models.CharField(blank=True, max_length=150)),
                ('cod_inventario_ref', models.CharField(blank=True, max_length=100)),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('PROCESADO', 'Procesado')], db_index=True, default='PENDIENTE', max_length=10)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('lugar_origen', models.CharField(blank=True, max_length=200)),
                ('observacion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Bien de Baja',
                'verbose_name_plural': 'Bienes de Baja',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(blank=True, max_length=150)),
                ('serie', models.CharField(blank=True, db_index=True, max_length=150)),
                ('cod_inventario', models.CharField(db_index=True, max_length=100, unique=True)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('estado', models.CharField(choices=[('OPERATIVO', 'Operativo'), ('EN_MANTENIMIENTO', 'En Mantenimiento'), ('DE_BAJA', 'De Baja'), ('ALMACEN', 'Almacén')], db_index=True, default='OPERATIVO', max_length=20)),
                ('dni_responsable', models.CharField(blank=True, max_length=20)),
                ('proveedor', models.CharField(blank=True, max_length=200)),
                ('orden_compra', models.CharField(blank=True, max_length=100)),
                ('observacion', models.TextField(blank=True)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('dependencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizacion.dependencia')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.marca')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositivos_a_cargo', to='users.userprofile')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizacion.sede')),
                ('subgerencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizacion.subgerencia')),
                ('tipo_dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispositivos', to='catalogo.tipodispositivo')),
                ('unidad_organica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizacion.unidadorganica')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
                'ordering': ['cod_inventario'],
            },
        ),
        migrations.CreateModel(
            name='DispMonitor',
            fields=[
                ('dispositivo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='monitor', serialize=False, to='inventario.dispositivo')),
                ('tamanio_pulgadas', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('resolucion', models.CharField(blank=True, max_length=30)),
                ('tipo_panel', models.CharField(blank=True, choices=[('LCD', 'LCD'), ('LED', 'LED'), ('IPS', 'IPS'), ('TN', 'TN'), ('VA', 'VA')], max_length=10)),
                ('conexion', models.CharField(blank=True, choices=[('HDMI', 'HDMI'), ('VGA', 'VGA'), ('DVI', 'DVI'), ('DP', 'DisplayPort')], max_length=10)),
            ],
            options={
                'verbose_name': 'Monitor',
                'verbose_name_plural': 'Monitores',
            },
        ),
        migrations.CreateModel(
            name='DispPeriferico',
            fields=[
                ('dispositivo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='periferico', serialize=False, to='inventario.dispositivo')),
                ('subtipo', models.CharField(blank=True, choices=[('TECLADO', 'Teclado'), ('MOUSE', 'Mouse'), ('WEBCAM', 'Webcam'), ('BIOMETRICO', 'Biométrico'), ('TABLET', 'Tablet'), ('LECTORA_QR', 'Lectora QR'), ('OTRO', 'Otro')], max_length=20)),
                ('conexion', models.CharField(blank=True, choices=[('USB', 'USB'), ('BLUETOOTH', 'Bluetooth'), ('PS2', 'PS/2'), ('INALAMBRICO', 'Inalámbrico')], max_length=15)),
            ],
            options={
                'verbose_name': 'Periférico',
                'verbose_name_plural': 'Periféricos',
            },
        ),
        migrations.CreateModel(
            name='DispRed',
            fields=[
                ('dispositivo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='red', serialize=False, to='inventario.dispositivo')),
                ('subtipo', models.CharField(blank=True, choices=[('SWITCH', 'Switch'), ('ROUTER', 'Router'), ('AP', 'Access Point'), ('NVR', 'NVR'), ('DVR', 'DVR'), ('UPS', 'UPS'), ('ESTABILIZADOR', 'Estabilizador'), ('SERVIDOR', 'Servidor')], max_length=20)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('mac', models.CharField(blank=True, max_length=17)),
                ('nombre_red', models.CharField(blank=True, max_length=100)),
                ('puertos', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Equipo de Red',
                'verbose_name_plural': 'Equipos de Red',
            },
        ),
        migrations.CreateModel(
            name='DispTelefono',
            fields=[
                ('dispositivo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='telefono', serialize=False, to='inventario.dispositivo')),
                ('extension', models.CharField(blank=True, max_length=20)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('mac', models.CharField(blank=True, max_length=17)),
            ],
            options={
                'verbose_name': 'Teléfono',
                'verbose_name_plural': 'Teléfonos',
            },
        ),
        migrations.CreateModel(
            name='BienBajaFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.ImageField(upload_to='bajas/fotos/%Y/%m/')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('slot', models.PositiveSmallIntegerField(default=1)),
                ('bien_baja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='inventario.bienbaja')),
            ],
            options={
                'verbose_name': 'Foto de Baja',
                'verbose_name_plural': 'Fotos de Baja',
                'ordering': ['slot'],
            },
        ),
        migrations.AddField(
            model_name='bienbaja',
            name='dispositivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bajas', to='inventario.dispositivo'),
        ),
        migrations.AddField(
            model_name='bienbaja',
            name='registrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bajas_registradas', to='users.userprofile'),
        ),
        migrations.CreateModel(
            name='DispImpresora',
            fields=[
                ('dispositivo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='impresora', serialize=False, to='inventario.dispositivo')),
                ('tipo', models.CharField(blank=True, choices=[('LASER', 'Láser'), ('INKJET', 'Inkjet'), ('MATRICIAL', 'Matricial'), ('MULTIFUNCION', 'Multifunción'), ('PLOTTER', 'Plotter'), ('TERMICA', 'Térmica')], max_length=20)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('mac', models.CharField(blank=True, max_length=17)),
                ('nombre_red', models.CharField(blank=True, max_length=100)),
                ('consumible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.consumible')),
            ],
            options={
                'verbose_name': 'Impresora',
                'verbose_name_plural': 'Impresoras',
            },
        ),
        migrations.CreateModel(
            name='DispComputadora',
            fields=[
                ('dispositivo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='computadora', serialize=False, to='inventario.dispositivo')),
                ('almacenamiento', models.CharField(blank=True, max_length=100)),
                ('ip', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('mac', models.CharField(blank=True, max_length=17)),
                ('nombre_equipo', models.CharField(blank=True, max_length=100)),
                ('dominio', models.CharField(blank=True, max_length=100)),
                ('tipo_pc', models.CharField(blank=True, choices=[('DESKTOP', 'Desktop'), ('LAPTOP', 'Laptop'), ('ALL_IN_ONE', 'All-in-One'), ('SERVIDOR', 'Servidor')], max_length=20)),
                ('cod_monitor', models.CharField(blank=True, max_length=100)),
                ('cod_teclado', models.CharField(blank=True, max_length=100)),
                ('licencia_office', models.BooleanField(default=False)),
                ('licencia_windows', models.BooleanField(default=False)),
                ('antivirus', models.BooleanField(default=False)),
                ('memoria_ram', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.memoriaram')),
                ('procesador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.procesador')),
                ('sistema_operativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.sistemaoperativo')),
            ],
            options={
                'verbose_name': 'Computadora',
                'verbose_name_plural': 'Computadoras',
            },
        ),
        migrations.CreateModel(
            name='DispCamara',
            fields=[
                ('dispositivo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='camara', serialize=False, to='inventario.dispositivo')),
                ('tipo_camara', models.CharField(blank=True, choices=[('DOMO', 'Domo'), ('BULLET', 'Bullet'), ('PTZ', 'PTZ')], max_length=10)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('mac', models.CharField(blank=True, max_length=17)),
                ('usuario_acceso', models.CharField(blank=True, max_length=100)),
                ('clave_acceso', models.CharField(blank=True, max_length=200)),
                ('nvr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camaras_conectadas', to='inventario.dispositivo')),
            ],
            options={
                'verbose_name': 'Cámara',
                'verbose_name_plural': 'Cámaras',
            },
        ),
    ]
