# Generated by Django 4.2.16 on 2026-05-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('tipo', models.CharField(choices=[('TONER', 'Tóner'), ('TINTA', 'Tinta'), ('PAPEL', 'Papel'), ('RIBBON', 'Ribbon'), ('OTRO', 'Otro')], default='OTRO', max_length=10)),
            ],
            options={
                'verbose_name': 'Consumible',
                'verbose_name_plural': 'Consumibles',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MemoriaRam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Memoria RAM',
                'verbose_name_plural': 'Memorias RAM',
                'ordering': ['capacidad'],
            },
        ),
        migrations.CreateModel(
            name='Procesador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Procesador',
                'verbose_name_plural': 'Procesadores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SistemaOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Sistema Operativo',
                'verbose_name_plural': 'Sistemas Operativos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('COMPUTADORA', 'Computadora'), ('IMPRESORA', 'Impresora'), ('MONITOR', 'Monitor'), ('PERIFERICO', 'Periférico'), ('RED', 'Red'), ('CAMARA', 'Cámara'), ('TELEFONO', 'Teléfono')], max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('tiene_subtabla', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Dispositivo',
                'verbose_name_plural': 'Tipos de Dispositivo',
                'ordering': ['nombre'],
            },
        ),
    ]
