# Generated by Django 4.2.16 on 2026-05-28 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_ide_siggo', models.IntegerField(db_index=True)),
                ('uni_ide_siggo', models.IntegerField()),
                ('uni_nombre_siggo', models.CharField(max_length=300)),
                ('cargo_descripcion', models.CharField(blank=True, max_length=300)),
                ('car_pri_siggo', models.IntegerField(default=0)),
                ('es_principal', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cargo de usuario',
                'verbose_name_plural': 'Cargos de usuario',
                'ordering': ['-es_principal', '-car_pri_siggo'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usu_ide_siggo', models.IntegerField(db_index=True, unique=True)),
                ('per_ide_siggo', models.IntegerField(db_index=True)),
                ('dni', models.CharField(db_index=True, max_length=20)),
                ('nombre_completo', models.CharField(max_length=300)),
                ('email', models.CharField(blank=True, max_length=250)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('JEFE_INFO', 'Jefe de Informática'), ('ENCARGADO_INFO', 'Encargado de Informática'), ('TECNICO', 'Técnico'), ('USUARIO', 'Usuario')], default='USUARIO', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('ultimo_sync_siggo', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cargo_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.usercargo')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='organizacion.sede')),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuario',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.AddField(
            model_name='usercargo',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='users.userprofile'),
        ),
        migrations.CreateModel(
            name='EncargadoActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desde', models.DateTimeField()),
                ('hasta', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.TextField(blank=True)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('autorizado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encargados_autorizados', to='users.userprofile')),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encargados_activos', to='users.userprofile')),
            ],
            options={
                'verbose_name': 'Encargado activo',
                'verbose_name_plural': 'Encargados activos',
                'ordering': ['-desde'],
            },
        ),
    ]
