# Generated by Django 4.2.16 on 2026-05-28 17:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('inventario', '0001_initial'),
        ('tickets', '0001_create_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('tipo_mantenimiento', models.CharField(choices=[('PREVENTIVO', 'Preventivo'), ('CORRECTIVO', 'Correctivo')], default='CORRECTIVO', max_length=15)),
                ('detalle_falla', models.TextField()),
                ('estado', models.CharField(choices=[('ENVIADO', 'Enviado'), ('EN_REVISION', 'En Revisión'), ('ASIGNADO', 'Asignado'), ('EN_ATENCION', 'En Atención'), ('SOLUCIONADO', 'Solucionado'), ('EN_MANTENIMIENTO', 'En Mantenimiento'), ('TERCERIZADO', 'Tercerizado'), ('FINALIZADO', 'Finalizado'), ('RECHAZADO', 'Rechazado')], db_index=True, default='ENVIADO', max_length=20)),
                ('ip_solicitante', models.GenericIPAddressField(blank=True, null=True)),
                ('nombre_responsable_snapshot', models.CharField(blank=True, max_length=300)),
                ('cargo_responsable_snapshot', models.CharField(blank=True, max_length=300)),
                ('fecha_creacion', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('fecha_asignacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('asignado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to='users.userprofile')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='inventario.dispositivo')),
                ('responsable_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_como_responsable_snapshot', to='users.userprofile')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_creados', to='users.userprofile')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_atendidos', to='users.userprofile')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='TicketTercerizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=200)),
                ('contacto', models.CharField(blank=True, max_length=200)),
                ('fecha_entrega_est', models.DateField(blank=True, null=True)),
                ('presupuesto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado_tercerizado', models.CharField(choices=[('ENVIADO', 'Enviado a empresa'), ('RECIBIDO', 'Recibido por empresa'), ('REPARADO', 'Reparado'), ('NO_REPARABLE', 'No reparable')], default='ENVIADO', max_length=15)),
                ('observacion', models.TextField(blank=True)),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tercerizados_registrados', to='users.userprofile')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tercerizado', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Ticket Tercerizado',
                'verbose_name_plural': 'Tickets Tercerizados',
            },
        ),
        migrations.CreateModel(
            name='TicketHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, max_length=20)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='tickets.ticket')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_acciones', to='users.userprofile')),
            ],
            options={
                'verbose_name': 'Historial de Ticket',
                'verbose_name_plural': 'Historial de Tickets',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='TicketDiagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_falla', models.CharField(max_length=200)),
                ('detalle_tecnico', models.TextField()),
                ('tipo_resultado', models.CharField(choices=[('MENOR', 'Menor — solución inmediata'), ('MAYOR', 'Mayor — requiere mantenimiento'), ('TERCERIZADO', 'Tercerizado — empresa externa')], max_length=15)),
                ('tiempo_estimado', models.CharField(blank=True, max_length=100)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnosticos', to='users.userprofile')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostico', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Diagnóstico',
                'verbose_name_plural': 'Diagnósticos',
            },
        ),
        migrations.CreateModel(
            name='TicketAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='tickets/adjuntos/%Y/%m/')),
                ('nombre_original', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Adjunto de Ticket',
                'verbose_name_plural': 'Adjuntos de Ticket',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='TicketAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_accion', models.CharField(max_length=100)),
                ('detalle', models.TextField()),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acciones_realizadas', to='users.userprofile')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Acción de Ticket',
                'verbose_name_plural': 'Acciones de Ticket',
                'ordering': ['fecha_registro'],
            },
        ),
    ]
