# Generated by Django 4.2.16 on 2026-05-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickethistorial',
            name='estado_anterior',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
