# Generated by Django 4.2.16 on 2026-05-28 17:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('tickets', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoOficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=50, unique=True)),
                ('archivo_pdf', models.FileField(upload_to='documentos/pdf/%Y/%m/')),
                ('fecha_generacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('generado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_generados', to='users.userprofile')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documento_oficial', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Documento Oficial',
                'verbose_name_plural': 'Documentos Oficiales',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
