from .base import *  # noqa

DEBUG = False

JWT_COOKIE_SECURE = True
JWT_COOKIE_SAMESITE = "Strict"

SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"
